---
- name: mariadb database create
  hosts: j
  tasks:
  - name: mariadb database create
    mysql_db: name=rantdata state=present

  - name: backup database
    mysql_db: name=rantdata state=dump  target=/tmp/{{ inventory_hostname }}.sql

  - name: Restore database
    mysql_db:  name=rantdata state=import target=/tmp/{{ inventory_hostname }}.sql

  - name: user creation on mysql
    mysql_user: name=rant host=localhost  password=12345  priv='*.*:ALL'  state=present
~                                                                                              
